name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Dolibarr 18.0
        run: git clone https://github.com/dolibarr/dolibarr -b 18.0 && pwd

      - name: Change directory in custom
        run: cd dolibarr/htdocs/custom && pwd

      - name: Build Saturne 1.2.0
        run: git clone https://github.com/evarisk/saturne

      - name: Change directory in saturne
        run: cd saturne && pwd
#  phpstan:
#    runs-on: ubuntu-latest
#    steps:s
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          path: admin/ class/ core/ lib/